name: Codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  collect:
    name: collect
    if: github.repository == 'aws/aws-cdk'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn install

      - name: Build CLI
        run: npx lerna run build --scope=aws-cdk

      - name: Run tests
        run: cd packages/aws-cdk && yarn test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: packages/aws-cdk/coverage
          fail_ci_if_error: true
          flags: suite.unit
          token: ${{ secrets.CODECOV_TOKEN }}
