name: github-merit-badger
on:
  pull_request_target:
    types:
      - opened

jobs:
  call-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: aws-github-ops/github-merit-badger@main
        id: merit-badger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          badges: '[beginning-contributor,repeat-contributor,valued-contributor,admired-contributor,star-contributor,distinguished-contributor]'
          thresholds: '[0,3,6,13,25,50]'
          badge-type: 'achievement'
          ignore-usernames: '[RomainMuller,rix0rrr,MrArnoldPalmer,iliapolo,otaviomacedo,madeline-k,kaizencc,comcalvi,corymhall,peterwoodworth,ryparker,TheRealAmazonKendra,vinayak-kukreja,Naumel,mrgrain,pahud,cgarvis,kellertk,HBobertz,sumupitchayan,pattasai,SankyRed,udaypant,aws-cdk-automation,dependabot[bot],mergify[bot]]'
