name: issue-reprioritization
on: 
  schedule:
    - cron: "0 0 * * 0"

jobs:
  issue-reprioritization:
    permissions:
      issues: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: kaizencc/issue-reprioritization-manager@main
        id: reprioritization-manager
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          original-label: p2
          new-label: p1
          reprioritization-threshold: 20
          project-column-url: https://github.com/aws/aws-cdk/projects/13#column-18002436
      - uses: kaizencc/pr-triage-manager@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          on-pulls: ${{ steps.reprioritization-manager.outputs.linked-pulls }}
