name: PR Prioritization Needs Attention Status
on:
  schedule:
    - cron: '0 7 * * 1-5'  # Runs at 7AM every day during weekdays
  workflow_dispatch:        # Manual trigger

jobs:
  update_project_status:
    if: github.repository == 'aws/aws-cdk'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Update Needs Attention Status
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/prioritization/update-attention-status.js')
            await script({github})