name: PR Prioritization AddedOn update

on:
  schedule:
    - cron: '0 */6 * * 1-5'  # Runs every 6 hours during weekdays
  workflow_dispatch:        # Manual trigger

jobs:
  update_added_on:
    if: github.repository == 'aws/aws-cdk'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name:  Update AddedOn field
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/prioritization/update-added-on.js')
            await script({github})
