name: replace-labels
on: 
  workflow_dispatch: {}
permissions: write-all
jobs:

  call-action:
    runs-on: ubuntu-latest
    steps:
      - uses: scanlonp/github-action-replace-labels@main
        id: replace-labels
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label-replacement: >
            {
              "@aws-cdk/alexa-ask": "aws-cdk-lib/alexa-ask",
              "@aws-cdk/assertions": "aws-cdk-lib/assertions",
              "@aws-cdk/assets": "aws-cdk-lib/assets",
              "@aws-cdk/aws-accessanalyzer": "aws-cdk-lib/aws-accessanalyzer",
              "@aws-cdk/aws-acmpca": "aws-cdk-lib/aws-acmpca",
              "@aws-cdk/aws-amazonmq": "aws-cdk-lib/aws-amazonmq",
              "@aws-cdk/aws-amplify": "@aws-cdk/aws-amplify-alpha",
              "@aws-cdk/aws-apigateway": "aws-cdk-lib/aws-apigateway",
              "@aws-cdk/aws-apigatewayv2": "@aws-cdk/aws-apigatewayv2-alpha",
              "@aws-cdk/aws-apigatewayv2-authorizers": "@aws-cdk/aws-apigatewayv2-authorizers-alpha",
              "@aws-cdk/aws-apigatewayv2-integrations": "@aws-cdk/aws-apigatewayv2-integrations-alpha",
              "@aws-cdk/aws-appconfig": "aws-cdk-lib/aws-appconfig",
              "@aws-cdk/aws-appflow": "aws-cdk-lib/aws-appflow",
              "@aws-cdk/aws-appintegrations": "aws-cdk-lib/aws-appintegrations",
              "@aws-cdk/aws-applicationautoscaling": "aws-cdk-lib/aws-applicationautoscaling",
              "@aws-cdk/aws-applicationinsights": "aws-cdk-lib/aws-applicationinsights",
              "@aws-cdk/aws-appmesh": "aws-cdk-lib/aws-appmesh",
              "@aws-cdk/aws-apprunner": "@aws-cdk/aws-apprunner-alpha",
              "@aws-cdk/aws-appstream": "aws-cdk-lib/aws-appstream",
              "@aws-cdk/aws-athena": "aws-cdk-lib/aws-athena",
              "@aws-cdk/aws-auditmanager": "aws-cdk-lib/aws-auditmanager",
              "@aws-cdk/aws-autoscaling": "aws-cdk-lib/aws-autoscaling",
              "@aws-cdk/aws-autoscaling-api": "aws-cdk-lib/aws-autoscaling-api",
              "@aws-cdk/aws-autoscaling-common": "aws-cdk-lib/aws-autoscaling-common",
              "@aws-cdk/aws-autoscaling-hooktargets": "aws-cdk-lib/aws-autoscaling-hooktargets",
              "@aws-cdk/aws-autoscalingplans": "aws-cdk-lib/aws-autoscalingplans",
              "@aws-cdk/aws-backup": "aws-cdk-lib/aws-backup",
              "@aws-cdk/aws-budgets": "aws-cdk-lib/aws-budgets",
              "@aws-cdk/aws-cassandra": "aws-cdk-lib/aws-cassandra",
              "@aws-cdk/aws-ce": "aws-cdk-lib/aws-ce",
              "@aws-cdk/aws-certificatemanager": "aws-cdk-lib/aws-certificatemanager",
              "@aws-cdk/aws-chatbot": "aws-cdk-lib/aws-chatbot",
              "@aws-cdk/aws-cloud9": "@aws-cdk/aws-cloud9-alpha",
              "@aws-cdk/aws-cloudformation": "aws-cdk-lib/aws-cloudformation",
              "@aws-cdk/aws-cloudfront": "aws-cdk-lib/aws-cloudfront",
              "@aws-cdk/aws-cloudfront-origins": "aws-cdk-lib/aws-cloudfront-origins",
              "@aws-cdk/aws-cloudtrail": "aws-cdk-lib/aws-cloudtrail",
              "@aws-cdk/aws-cloudwatch": "aws-cdk-lib/aws-cloudwatch",
              "@aws-cdk/aws-cloudwatch-actions": "aws-cdk-lib/aws-cloudwatch-actions",
              "@aws-cdk/aws-codeartifact": "aws-cdk-lib/aws-codeartifact",
              "@aws-cdk/aws-codebuild": "aws-cdk-lib/aws-codebuild",
              "@aws-cdk/aws-codecommit": "aws-cdk-lib/aws-codecommit",
              "@aws-cdk/aws-codedeploy": "aws-cdk-lib/aws-codedeploy",
              "@aws-cdk/aws-codeguruprofiler": "aws-cdk-lib/aws-codeguruprofiler",
              "@aws-cdk/aws-codegurureviewer": "aws-cdk-lib/aws-codegurureviewer",
              "@aws-cdk/aws-codepipeline": "aws-cdk-lib/aws-codepipeline",
              "@aws-cdk/aws-codepipeline-actions": "aws-cdk-lib/aws-codepipeline-actions",
              "@aws-cdk/aws-codestar": "@aws-cdk/aws-codestar-alpha",
              "@aws-cdk/aws-codestarconnections": "aws-cdk-lib/aws-codestarconnections",
              "@aws-cdk/aws-codestarnotifications": "aws-cdk-lib/aws-codestarnotifications",
              "@aws-cdk/aws-cognito": "aws-cdk-lib/aws-cognito",
              "@aws-cdk/aws-cognito-identitypool": "@aws-cdk/aws-cognito-identitypool-alpha",
              "@aws-cdk/aws-config": "aws-cdk-lib/aws-config",
              "@aws-cdk/aws-customerprofiles": "aws-cdk-lib/aws-customerprofiles",
              "@aws-cdk/aws-databrew": "aws-cdk-lib/aws-databrew",
              "@aws-cdk/aws-datapipeline": "aws-cdk-lib/aws-datapipeline",
              "@aws-cdk/aws-datasync": "aws-cdk-lib/aws-datasync",
              "@aws-cdk/aws-dax": "aws-cdk-lib/aws-dax",
              "@aws-cdk/aws-detective": "aws-cdk-lib/aws-detective",
              "@aws-cdk/aws-devopsguru": "aws-cdk-lib/aws-devopsguru",
              "@aws-cdk/aws-directoryservice": "aws-cdk-lib/aws-directoryservice",
              "@aws-cdk/aws-dlm": "aws-cdk-lib/aws-dlm",
              "@aws-cdk/aws-dms": "aws-cdk-lib/aws-dms",
              "@aws-cdk/aws-docdb": "aws-cdk-lib/aws-docdb",
              "@aws-cdk/aws-dynamodb": "aws-cdk-lib/aws-dynamodb",
              "@aws-cdk/aws-ec2": "aws-cdk-lib/aws-ec2",
              "@aws-cdk/aws-ecr": "aws-cdk-lib/aws-ecr",
              "@aws-cdk/aws-ecr-assets": "aws-cdk-lib/aws-ecr-assets",
              "@aws-cdk/aws-ecs": "aws-cdk-lib/aws-ecs",
              "@aws-cdk/aws-ecs-patterns": "aws-cdk-lib/aws-ecs-patterns",
              "@aws-cdk/aws-efs": "aws-cdk-lib/aws-efs",
              "@aws-cdk/aws-eks": "aws-cdk-lib/aws-eks",
              "@aws-cdk/aws-elasticache": "aws-cdk-lib/aws-elasticache",
              "@aws-cdk/aws-elasticbeanstalk": "aws-cdk-lib/aws-elasticbeanstalk",
              "@aws-cdk/aws-elasticloadbalancing": "aws-cdk-lib/aws-elasticloadbalancing",
              "@aws-cdk/aws-elasticloadbalancingv2": "aws-cdk-lib/aws-elasticloadbalancingv2",
              "@aws-cdk/aws-elasticloadbalancingv2-actions": "aws-cdk-lib/aws-elasticloadbalancingv2-actions",
              "@aws-cdk/aws-elasticloadbalancingv2-targets": "aws-cdk-lib/aws-elasticloadbalancingv2-targets",
              "@aws-cdk/aws-elasticsearch": "aws-cdk-lib/aws-elasticsearch",
              "@aws-cdk/aws-emr": "aws-cdk-lib/aws-emr",
              "@aws-cdk/aws-emrcontainers": "aws-cdk-lib/aws-emrcontainers",
              "@aws-cdk/aws-events": "aws-cdk-lib/aws-events",
              "@aws-cdk/aws-events-targets": "aws-cdk-lib/aws-events-targets",
              "@aws-cdk/aws-eventschemas": "aws-cdk-lib/aws-eventschemas",
              "@aws-cdk/aws-finspace": "aws-cdk-lib/aws-finspace",
              "@aws-cdk/aws-fis": "aws-cdk-lib/aws-fis",
              "@aws-cdk/aws-fms": "aws-cdk-lib/aws-fms",
              "@aws-cdk/aws-frauddetector": "aws-cdk-lib/aws-frauddetector",
              "@aws-cdk/aws-fsx": "aws-cdk-lib/aws-fsx",
              "@aws-cdk/aws-gamelift": "@aws-cdk/aws-gamelift-alpha",
              "@aws-cdk/aws-globalaccelerator": "aws-cdk-lib/aws-globalaccelerator",
              "@aws-cdk/aws-globalaccelerator-endpoints": "aws-cdk-lib/aws-globalaccelerator-endpoints",
              "@aws-cdk/aws-glue": "@aws-cdk/aws-glue-alpha",
              "@aws-cdk/aws-greengrass": "aws-cdk-lib/aws-greengrass",
              "@aws-cdk/aws-greengrassv2": "aws-cdk-lib/aws-greengrassv2",
              "@aws-cdk/aws-groundstation": "aws-cdk-lib/aws-groundstation",
              "@aws-cdk/aws-guardduty": "aws-cdk-lib/aws-guardduty",
              "@aws-cdk/aws-iam": "aws-cdk-lib/aws-iam",
              "@aws-cdk/aws-imagebuilder": "aws-cdk-lib/aws-imagebuilder",
              "@aws-cdk/aws-inspector": "aws-cdk-lib/aws-inspector",
              "@aws-cdk/aws-iot": "@aws-cdk/aws-iot-alpha",
              "@aws-cdk/aws-iot-actions": "@aws-cdk/aws-iot-actions-alpha",
              "@aws-cdk/aws-iot1click": "aws-cdk-lib/aws-iot1click",
              "@aws-cdk/aws-iotanalytics": "aws-cdk-lib/aws-iotanalytics",
              "@aws-cdk/aws-iotevents": "@aws-cdk/aws-iotevents-alpha",
              "@aws-cdk/aws-iotevents-actions": "@aws-cdk/aws-iotevents-actions-alpha",
              "@aws-cdk/aws-iotfleethub": "aws-cdk-lib/aws-iotfleethub",
              "@aws-cdk/aws-iotsitewise": "aws-cdk-lib/aws-iotsitewise",
              "@aws-cdk/aws-iotthingsgraph": "aws-cdk-lib/aws-iotthingsgraph",
              "@aws-cdk/aws-iotwireless": "aws-cdk-lib/aws-iotwireless",
              "@aws-cdk/aws-ivs": "@aws-cdk/aws-ivs-alpha",
              "@aws-cdk/aws-kendra": "aws-cdk-lib/aws-kendra",
              "@aws-cdk/aws-kinesis": "aws-cdk-lib/aws-kinesis",
              "@aws-cdk/aws-kinesisanalytics": "aws-cdk-lib/aws-kinesisanalytics",
              "@aws-cdk/aws-kinesisanalytics-flink": "@aws-cdk/aws-kinesisanalytics-flink-alpha",
              "@aws-cdk/aws-kinesisfirehose": "@aws-cdk/aws-kinesisfirehose-alpha",
              "@aws-cdk/aws-kms": "aws-cdk-lib/aws-kms",
              "@aws-cdk/aws-lakeformation": "aws-cdk-lib/aws-lakeformation",
              "@aws-cdk/aws-lambda": "aws-cdk-lib/aws-lambda",
              "@aws-cdk/aws-lambda-destinations": "aws-cdk-lib/aws-lambda-destinations",
              "@aws-cdk/aws-lambda-event-sources": "aws-cdk-lib/aws-lambda-event-sources",
              "@aws-cdk/aws-lambda-go": "@aws-cdk/aws-lambda-go-alpha",
              "@aws-cdk/aws-lambda-nodejs": "aws-cdk-lib/aws-lambda-nodejs",
              "@aws-cdk/aws-lambda-python": "@aws-cdk/aws-lambda-python-alpha",
              "@aws-cdk/aws-licensemanager": "aws-cdk-lib/aws-licensemanager",
              "@aws-cdk/aws-logs": "aws-cdk-lib/aws-logs",
              "@aws-cdk/aws-logs-destinations": "aws-cdk-lib/aws-logs-destinations",
              "@aws-cdk/aws-lookoutmetrics": "aws-cdk-lib/aws-lookoutmetrics",
              "@aws-cdk/aws-lookoutvision": "aws-cdk-lib/aws-lookoutvision",
              "@aws-cdk/aws-macie": "aws-cdk-lib/aws-macie",
              "@aws-cdk/aws-managedblockchain": "aws-cdk-lib/aws-managedblockchain",
              "@aws-cdk/aws-mediaconnect": "aws-cdk-lib/aws-mediaconnect",
              "@aws-cdk/aws-mediaconvert": "aws-cdk-lib/aws-mediaconvert",
              "@aws-cdk/aws-medialive": "aws-cdk-lib/aws-medialive",
              "@aws-cdk/aws-mediastore": "aws-cdk-lib/aws-mediastore",
              "@aws-cdk/aws-mediapackage": "package/aws-mediaaws-cdk-lib",
              "@aws-cdk/aws-msk": "@aws-cdk/aws-msk-alpha",
              "@aws-cdk/aws-mwaa": "aws-cdk-lib/aws-mwaa",
              "@aws-cdk/aws-neptune": "@aws-cdk/aws-neptune-alpha",
              "@aws-cdk/aws-networkfirewall": "aws-cdk-lib/aws-networkfirewall",
              "@aws-cdk/aws-networkmanager": "aws-cdk-lib/aws-networkmanager",
              "@aws-cdk/aws-nimblestudio": "aws-cdk-lib/aws-nimblestudio",
              "@aws-cdk/aws-opensearch": "aws-cdk-lib/aws-opensearch",
              "@aws-cdk/aws-opsworks": "aws-cdk-lib/aws-opsworks",
              "@aws-cdk/aws-opsworkscm": "aws-cdk-lib/aws-opsworkscm",
              "@aws-cdk/aws-personalize": "aws-cdk-lib/aws-personalize",
              "@aws-cdk/aws-pinpoint": "aws-cdk-lib/aws-pinpoint",
              "@aws-cdk/aws-pinpointemail": "aws-cdk-lib/aws-pinpointemail",
              "@aws-cdk/aws-qldb": "aws-cdk-lib/aws-qldb",
              "@aws-cdk/aws-quicksight": "aws-cdk-lib/aws-quicksight",
              "@aws-cdk/aws-ram": "aws-cdk-lib/aws-ram",
              "@aws-cdk/aws-rds": "aws-cdk-lib/aws-rds",
              "@aws-cdk/aws-redshift": "@aws-cdk/aws-redshift-alpha",
              "@aws-cdk/aws-resourcegroups": "aws-cdk-lib/aws-resourcegroups",
              "@aws-cdk/aws-robomaker": "aws-cdk-lib/aws-robomaker",
              "@aws-cdk/aws-route53": "aws-cdk-lib/aws-route53",
              "@aws-cdk/aws-route53-patterns": "aws-cdk-lib/aws-route53-patterns",
              "@aws-cdk/aws-route53-targets": "aws-cdk-lib/aws-route53-targets",
              "@aws-cdk/aws-route53resolver": "@aws-cdk/aws-route53resolver-alpha",
              "@aws-cdk/aws-s3": "aws-cdk-lib/aws-s3",
              "@aws-cdk/aws-s3-assets": "aws-cdk-lib/aws-s3-assets",
              "@aws-cdk/aws-s3-deployment": "aws-cdk-lib/aws-s3-deployment",
              "@aws-cdk/aws-s3-notifications": "aws-cdk-lib/aws-s3-notifications",
              "@aws-cdk/aws-s3objectlambda": "@aws-cdk/aws-s3objectlambda-alpha",
              "@aws-cdk/aws-s3outposts": "aws-cdk-lib/aws-s3outposts",
              "@aws-cdk/aws-sagemaker": "@aws-cdk/aws-sagemaker-alpha",
              "@aws-cdk/aws-sam": "aws-cdk-lib/aws-sam",
              "@aws-cdk/aws-sdb": "aws-cdk-lib/aws-sdb",
              "@aws-cdk/aws-secretsmanager": "aws-cdk-lib/aws-secretsmanager",
              "@aws-cdk/aws-securityhub": "aws-cdk-lib/aws-securityhub",
              "@aws-cdk/aws-servicecatalog": "aws-cdk-lib/aws-servicecatalog",
              "@aws-cdk/aws-servicecatalogappregistry": "@aws-cdk/aws-servicecatalogappregistry-alpha",
              "@aws-cdk/aws-servicediscovery": "aws-cdk-lib/aws-servicediscovery",
              "@aws-cdk/aws-ses": "aws-cdk-lib/aws-ses",
              "@aws-cdk/aws-ses-actions": "aws-cdk-lib/aws-ses-actions",
              "@aws-cdk/aws-signer": "aws-cdk-lib/aws-signer",
              "@aws-cdk/aws-sns": "aws-cdk-lib/aws-sns",
              "@aws-cdk/aws-sns-subscriptions": "aws-cdk-lib/aws-sns-subscriptions",
              "@aws-cdk/aws-sqs": "aws-cdk-lib/aws-sqs",
              "@aws-cdk/aws-ssm": "aws-cdk-lib/aws-ssm",
              "@aws-cdk/aws-sso": "aws-cdk-lib/aws-sso",
              "@aws-cdk/aws-stepfunctions": "aws-cdk-lib/aws-stepfunctions",
              "@aws-cdk/aws-stepfunctions-tasks": "aws-cdk-lib/aws-stepfunctions-tasks",
              "@aws-cdk/aws-synthetics": "@aws-cdk/aws-synthetics-alpha",
              "@aws-cdk/aws-timestream": "aws-cdk-lib/aws-timestream",
              "@aws-cdk/aws-transfer": "aws-cdk-lib/aws-transfer",
              "@aws-cdk/aws-waf": "aws-cdk-lib/aws-waf",
              "@aws-cdk/aws-wafregional": "aws-cdk-lib/aws-wafregional",
              "@aws-cdk/aws-wafv2": "aws-cdk-lib/aws-wafv2",
              "@aws-cdk/aws-workspaces": "aws-cdk-lib/aws-workspaces",
              "@aws-cdk/aws-xray": "aws-cdk-lib/aws-xray",
              "@aws-cdk/cfnspec": "aws-cdk-lib/cfnspec",
              "@aws-cdk/cloud-assembly-schema": "aws-cdk-lib/cloud-assembly-schema",
              "@aws-cdk/cloudformation-diff": "aws-cdk-lib/cloudformation-diff",
              "@aws-cdk/cloudformation-include": "aws-cdk-lib/cloudformation-include",
              "@aws-cdk/core": "aws-cdk-lib/core",
              "@aws-cdk/custom-resources": "aws-cdk-lib/custom-resources",
              "@aws-cdk/cx-api": "aws-cdk-lib/cx-api",
              "@aws-cdk/aws-lambda-layer-awscli": "aws-cdk-lib/aws-lambda-layer-awscli",
              "@aws-cdk/aws-lambda-layer-kubectl": "aws-cdk-lib/aws-lambda-layer-kubectl",
              "@aws-cdk/pipelines": "aws-cdk-lib/pipelines",
              "@aws-cdk/region-info": "aws-cdk-lib/region-info",
              "@aws-cdk/aws-yaml-cfn": "aws-cdk-lib/aws-yaml-cfn",
              "@aws-cdk/aws-lightsail": "aws-cdk-lib/aws-lightsail",
              "@aws-cdk/aws-aps": "aws-cdk-lib/aws-aps",
              "@aws-cdk/triggers": "aws-cdk-lib/triggers",
              "@aws-cdk/integ-tests": "@aws-cdk/integ-tests-alpha"
            }