# Automated actions for PRs against the v2-main branch
name: v2
on:
  pull_request:
    branches:
      - v2-main
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  # Run yarn pkglint on merge forward PRs and commit the results
  pkglint:
    permissions:
      pull-requests: write
      contents: write
    if: contains(github.event.pull_request.labels.*.name, 'pr/forward-merge')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: lint
        run: |-
          yarn install --frozen-lockfile
          yarn pkglint
      - name: push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'automatic pkglint fixes'
